config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasklists#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create]
  resources :tasklists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  belongs_to :user, optional: true
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasklists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
    
private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasklists = user.tasklists.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to tasklists_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :require_user_logged_in,only:[:show,:edit,:update,:destroy]
  before_action :set_tasklist, only: [:show, :edit, :update, :destroy]
  
  def index
    if logged_in?
      @tasklists = current_user.tasklists.order(id: :desc).page(params[:page]).per(3)
    end
  end

  def show
  end

  def new
    @tasklist = current_user.tasklists.build
  end

  def create
    @tasklist = current_user.tasklists.build(tasklist_params)
    
    if @tasklist.save
      flash[:success] = 'タスクが正常に追加されました'
      redirect_to root_url
    else
      @tasklists = current_user.tasklists.order(id: :desc).page(params[:page]).per(3)
      flash.now[:danger] = 'タスクが追加されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @tasklist.update(tasklist_params)
      flash[:success]= 'タスクは正常に更新されました'
      redirect_to root_url
    else
      flash.now[:dangeer]= 'タスクは正常に更新されませんでした'
      render :edit
    end
  end

  def destroy
    @tasklist.destroy
    
    flash[:success] = 'タスクは正常に削除されました'
    redirect_to tasklists_url
  end

private

  def set_tasklist
    @tasklist = Tasklist.find(params[:id])
  end

  def tasklist_params
    params.require(:tasklist).permit(:content, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])  
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasklists.html.erb
<%flash.each do |tasklist_type, tasklist| %>

<div class="alert alert-<%= tasklist_type %>"><%= tasklist %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Task for God.</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
      
      <% if logged_in? %>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to '新規タスク', new_tasklist_path, rel: 'nav-link' %></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </div>
      <% else %>
        <a class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></a>
        <a class="nav-item">><%= link_to 'Login', login_path, class: 'nav-link' %></a>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container"></div>
      <%= render 'layouts/flash_tasklists'%>
      
    <%= yield %>
  </body>
</html>

app/views/tasklists/_form.html.erb
<div class ="row">
  <div class="col-6">
    <%= form_with(model: tasklist, local: true)do |f| %>
      <% if tasklist.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul>
            <% tasklist.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class = "form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class:'form-control' %>
      </div>
      
      <div class = "form-group">
        <%= f.label :content, 'タスク'%>
        <%= f.text_field :content, class:'form-control' %>
      </div>
      
      <%= f.submit '完了', class:'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasklists/edit.html.erb
<h1>id: <%= @tasklist.id %> のタスク編集ページ</h1>

<%=  render 'form', tasklist: @tasklist %>

app/views/tasklists/index.html.erb
<% if logged_in? %>

<h1>タスク一覧</h1>

<% if @tasklists.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>タスク</th>
      </tr>
    </thead>
    <tbody>
      <% @tasklists.each do |tasklist| %>
        <tr>
          <td><%= link_to tasklist.id, tasklist %></td>
          <td><%= tasklist.title %></td>
          <td><%= tasklist.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @tasklists %>
  </div>
 <% end %>
 
<%=link_to '新規タスクの追加', new_tasklist_path, class: "btn btn-primary" %>

<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>Task for God.</h1>
    <p class="lead">ええ〜〜<br>タスク管理しちゃうの〜〜〜？？？</p>
    <%= link_to '甘んじてタスク管理する' , signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>
<% end %>

app/views/tasklists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%=  render 'form', tasklist: @tasklist %>

app/views/tasklists/show.html.erb
<h1>id: <%= @tasklist.id %>のタスク詳細</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @tasklist.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @tasklist.title %></td>
  </tr>
  <tr>
    <th>メッセージ</th>
    <td><%= @tasklist.content %></td>
  </tr>
</table>

<%= link_to'このタスクを編集する',edit_tasklist_path(@tasklist), class: 'btn btn-light'%>
<%= link_to 'このタスクを削除する',@tasklist, method: :delete, data: {confirm: '本当に削除してもよろしいでしょうか？'}, class: 'btn btn-danger'%>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>神の仲間入りする。</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user,local:true) do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="formgroup">
        <%= f.label :name, '神名'%>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      
      <div class="formgroup">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control'%>
      </div>
      
      <div class= "formgroup">
        <%= f.label :password,'Password'%>
        <%= f.password_field :password, class:'form-control'%>
      </div>
      
      <div class="formgroup">
        <%= f.label :password_confirmation, 'Password確認' %>
        <%= f.password_field :password, class: 'form-control'%>
      </div>
      
      <%= f.submit '神の仲間入り', class: 'btn btn-primary btn-block'%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>